const data = [
    {
        timestamp: 1658235600000,
        "CSBPL IS1 Inverter1 Unit1 Input Current_1 (A)": 0,
        "CSBPL IS1 Inverter1 Unit1 Input Current_2 (A)": 6.5,
        "CSBPL IS1 Inverter1 Unit1 Input Current_3 (A)": 5.6,
        "CSBPL IS1 Inverter1 Unit1 Input Current_4 (A)": 7.5,
        "CSBPL IS1 Inverter1 Unit1 Input Current_5 (A)": 6.5,
        "CSBPL IS1 Inverter1 Unit1 Input Current_6 (A)": 7.5,
        "CSBPL IS1 Inverter1 Unit1 Input Current_7 (A)": 7.8,
        "CSBPL IS1 Inverter1 Unit1 Input Current_8 (A)": 7.5,
        "CSBPL IS1 Inverter1 Unit1 Input Current_9 (A)": 7.5,
        "CSBPL IS1 Inverter1 Unit1 Input Current_10 (A)": 0,
        "CSBPL IS1 Inverter1 Unit1 Input Current_11 (A)": 0,
        "CSBPL IS1 Inverter1 Unit2 Input Current_1 (A)": 7.6,
        "CSBPL IS1 Inverter1 Unit2 Input Current_2 (A)": 8,
        "CSBPL IS1 Inverter1 Unit2 Input Current_3 (A)": 7.7,
        "CSBPL IS1 Inverter1 Unit2 Input Current_4 (A)": 7.3,
        "CSBPL IS1 Inverter1 Unit2 Input Current_5 (A)": 7.4,
        "CSBPL IS1 Inverter1 Unit2 Input Current_6 (A)": 7.6,
        "CSBPL IS1 Inverter1 Unit2 Input Current_7 (A)": 7.6,
        "CSBPL IS1 Inverter1 Unit2 Input Current_8 (A)": 7.6,
        "CSBPL IS1 Inverter1 Unit2 Input Current_9 (A)": 7.9,
        "CSBPL IS1 Inverter1 Unit2 Input Current_10 (A)": 0,
        "CSBPL IS1 Inverter1 Unit2 Input Current_11 (A)": 0,
        "CSBPL IS1 Inverter2 Unit1 Input Current_1 (A)": 8.1,
        "CSBPL IS1 Inverter2 Unit1 Input Current_2 (A)": 8.1,
        "CSBPL IS1 Inverter2 Unit1 Input Current_3 (A)": 7.8,
        "CSBPL IS1 Inverter2 Unit1 Input Current_4 (A)": 8.1,
        "CSBPL IS1 Inverter2 Unit1 Input Current_5 (A)": 7.8,
        "CSBPL IS1 Inverter2 Unit1 Input Current_6 (A)": 7.9,
        "CSBPL IS1 Inverter2 Unit1 Input Current_7 (A)": 7.9,
        "CSBPL IS1 Inverter2 Unit1 Input Current_8 (A)": 7.8,
        "CSBPL IS1 Inverter2 Unit1 Input Current_9 (A)": 7.9,
        "CSBPL IS1 Inverter2 Unit1 Input Current_10 (A)": 0,
        "CSBPL IS1 Inverter2 Unit1 Input Current_11 (A)": 0,
        "CSBPL IS1 Inverter2 Unit2 Input Current_1 (A)": 0,
        "CSBPL IS1 Inverter2 Unit2 Input Current_2 (A)": 7.8,
        "CSBPL IS1 Inverter2 Unit2 Input Current_3 (A)": 7.8,
        "CSBPL IS1 Inverter2 Unit2 Input Current_4 (A)": 7,
        "CSBPL IS1 Inverter2 Unit2 Input Current_5 (A)": 7.9,
        "CSBPL IS1 Inverter2 Unit2 Input Current_6 (A)": 6.9,
        "CSBPL IS1 Inverter2 Unit2 Input Current_7 (A)": 8.1,
        "CSBPL IS1 Inverter2 Unit2 Input Current_8 (A)": 8,
        "CSBPL IS1 Inverter2 Unit2 Input Current_9 (A)": 8,
        "CSBPL IS1 Inverter2 Unit2 Input Current_10 (A)": 7.9,
        "CSBPL IS1 Inverter2 Unit2 Input Current_11 (A)": 0,
        "CSBPL IS1 Inverter3 Unit2 Input Current_1 (A)": 8.1,
        "CSBPL IS1 Inverter3 Unit2 Input Current_2 (A)": 8,
        "CSBPL IS1 Inverter3 Unit2 Input Current_3 (A)": 7.9,
        "CSBPL IS1 Inverter3 Unit2 Input Current_4 (A)": 7.9,
        "CSBPL IS1 Inverter3 Unit2 Input Current_5 (A)": 8,
        "CSBPL IS1 Inverter3 Unit2 Input Current_6 (A)": 8.2,
        "CSBPL IS1 Inverter3 Unit2 Input Current_7 (A)": 8,
        "CSBPL IS1 Inverter3 Unit2 Input Current_8 (A)": 7.9,
        "CSBPL IS1 Inverter3 Unit2 Input Current_9 (A)": 8,
        "CSBPL IS1 Inverter3 Unit2 Input Current_10 (A)": 0,
        "CSBPL IS1 Inverter3 Unit2 Input Current_11 (A)": 0,
        "CSBPL IS1 Inverter3 Unit1 Input Current_1 (A)": 7.9,
        "CSBPL IS1 Inverter3 Unit1 Input Current_2 (A)": 7.8,
        "CSBPL IS1 Inverter3 Unit1 Input Current_3 (A)": 7.8,
        "CSBPL IS1 Inverter3 Unit1 Input Current_4 (A)": 8,
        "CSBPL IS1 Inverter3 Unit1 Input Current_5 (A)": 8.1,
        "CSBPL IS1 Inverter3 Unit1 Input Current_6 (A)": 7.5,
        "CSBPL IS1 Inverter3 Unit1 Input Current_7 (A)": 8.1,
        "CSBPL IS1 Inverter3 Unit1 Input Current_8 (A)": 7.1,
        "CSBPL IS1 Inverter3 Unit1 Input Current_9 (A)": 7.8,
        "CSBPL IS1 Inverter3 Unit1 Input Current_10 (A)": 0,
        "CSBPL IS1 Inverter3 Unit1 Input Current_11 (A)": 0,
        "CSBPL IS1 Inverter4 Unit1 Input Current_1 (A)": 7.8,
        "CSBPL IS1 Inverter4 Unit1 Input Current_2 (A)": 7.8,
        "CSBPL IS1 Inverter4 Unit1 Input Current_3 (A)": 7.9,
        "CSBPL IS1 Inverter4 Unit1 Input Current_4 (A)": 7.3,
        "CSBPL IS1 Inverter4 Unit1 Input Current_5 (A)": 8,
        "CSBPL IS1 Inverter4 Unit1 Input Current_6 (A)": 8,
        "CSBPL IS1 Inverter4 Unit1 Input Current_7 (A)": 7.9,
        "CSBPL IS1 Inverter4 Unit1 Input Current_8 (A)": 7.6,
        "CSBPL IS1 Inverter4 Unit1 Input Current_9 (A)": 7.5,
        "CSBPL IS1 Inverter4 Unit1 Input Current_10 (A)": 0,
        "CSBPL IS1 Inverter4 Unit1 Input Current_11 (A)": 0,
        "CSBPL IS1 Inverter4 Unit2 Input Current_1 (A)": 7.4,
        "CSBPL IS1 Inverter4 Unit2 Input Current_2 (A)": 7.7,
        "CSBPL IS1 Inverter4 Unit2 Input Current_3 (A)": 7.5,
        "CSBPL IS1 Inverter4 Unit2 Input Current_4 (A)": 7.6,
        "CSBPL IS1 Inverter4 Unit2 Input Current_5 (A)": 7.1,
        "CSBPL IS1 Inverter4 Unit2 Input Current_6 (A)": 0,
        "CSBPL IS1 Inverter4 Unit2 Input Current_7 (A)": 6.9,
        "CSBPL IS1 Inverter4 Unit2 Input Current_8 (A)": 6.8,
        "CSBPL IS1 Inverter4 Unit2 Input Current_9 (A)": 6.9,
        "CSBPL IS1 Inverter4 Unit2 Input Current_10 (A)": 7,
        "CSBPL IS1 Inverter4 Unit2 Input Current_11 (A)": 0,
    },
    {
        timestamp: 1658235660000,
        "CSBPL IS1 Inverter1 Unit1 Input Current_1 (A)": 0,
        "CSBPL IS1 Inverter1 Unit1 Input Current_2 (A)": 6.5,
        "CSBPL IS1 Inverter1 Unit1 Input Current_3 (A)": 5.6,
        "CSBPL IS1 Inverter1 Unit1 Input Current_4 (A)": 7.4,
        "CSBPL IS1 Inverter1 Unit1 Input Current_5 (A)": 6.5,
        "CSBPL IS1 Inverter1 Unit1 Input Current_6 (A)": 7.4,
        "CSBPL IS1 Inverter1 Unit1 Input Current_7 (A)": 7.8,
        "CSBPL IS1 Inverter1 Unit1 Input Current_8 (A)": 7.5,
        "CSBPL IS1 Inverter1 Unit1 Input Current_9 (A)": 7.4,
        "CSBPL IS1 Inverter1 Unit1 Input Current_10 (A)": 0,
        "CSBPL IS1 Inverter1 Unit1 Input Current_11 (A)": 0,
        "CSBPL IS1 Inverter1 Unit2 Input Current_1 (A)": 7.5,
        "CSBPL IS1 Inverter1 Unit2 Input Current_2 (A)": 7.9,
        "CSBPL IS1 Inverter1 Unit2 Input Current_3 (A)": 7.6,
        "CSBPL IS1 Inverter1 Unit2 Input Current_4 (A)": 7.2,
        "CSBPL IS1 Inverter1 Unit2 Input Current_5 (A)": 7.3,
        "CSBPL IS1 Inverter1 Unit2 Input Current_6 (A)": 7.5,
        "CSBPL IS1 Inverter1 Unit2 Input Current_7 (A)": 7.6,
        "CSBPL IS1 Inverter1 Unit2 Input Current_8 (A)": 7.5,
        "CSBPL IS1 Inverter1 Unit2 Input Current_9 (A)": 7.8,
        "CSBPL IS1 Inverter1 Unit2 Input Current_10 (A)": 0,
        "CSBPL IS1 Inverter1 Unit2 Input Current_11 (A)": 0,
        "CSBPL IS1 Inverter2 Unit1 Input Current_1 (A)": 8.1,
        "CSBPL IS1 Inverter2 Unit1 Input Current_2 (A)": 7.9,
        "CSBPL IS1 Inverter2 Unit1 Input Current_3 (A)": 7.7,
        "CSBPL IS1 Inverter2 Unit1 Input Current_4 (A)": 7.9,
        "CSBPL IS1 Inverter2 Unit1 Input Current_5 (A)": 7.7,
        "CSBPL IS1 Inverter2 Unit1 Input Current_6 (A)": 7.8,
        "CSBPL IS1 Inverter2 Unit1 Input Current_7 (A)": 7.8,
        "CSBPL IS1 Inverter2 Unit1 Input Current_8 (A)": 7.7,
        "CSBPL IS1 Inverter2 Unit1 Input Current_9 (A)": 7.8,
        "CSBPL IS1 Inverter2 Unit1 Input Current_10 (A)": 0,
        "CSBPL IS1 Inverter2 Unit1 Input Current_11 (A)": 0,
        "CSBPL IS1 Inverter2 Unit2 Input Current_1 (A)": 0,
        "CSBPL IS1 Inverter2 Unit2 Input Current_2 (A)": 7.7,
        "CSBPL IS1 Inverter2 Unit2 Input Current_3 (A)": 7.7,
        "CSBPL IS1 Inverter2 Unit2 Input Current_4 (A)": 6.9,
        "CSBPL IS1 Inverter2 Unit2 Input Current_5 (A)": 7.9,
        "CSBPL IS1 Inverter2 Unit2 Input Current_6 (A)": 6.9,
        "CSBPL IS1 Inverter2 Unit2 Input Current_7 (A)": 8,
        "CSBPL IS1 Inverter2 Unit2 Input Current_8 (A)": 7.9,
        "CSBPL IS1 Inverter2 Unit2 Input Current_9 (A)": 7.9,
        "CSBPL IS1 Inverter2 Unit2 Input Current_10 (A)": 7.8,
        "CSBPL IS1 Inverter2 Unit2 Input Current_11 (A)": 0,
        "CSBPL IS1 Inverter3 Unit2 Input Current_1 (A)": 8,
        "CSBPL IS1 Inverter3 Unit2 Input Current_2 (A)": 7.9,
        "CSBPL IS1 Inverter3 Unit2 Input Current_3 (A)": 7.8,
        "CSBPL IS1 Inverter3 Unit2 Input Current_4 (A)": 7.8,
        "CSBPL IS1 Inverter3 Unit2 Input Current_5 (A)": 8,
        "CSBPL IS1 Inverter3 Unit2 Input Current_6 (A)": 8.2,
        "CSBPL IS1 Inverter3 Unit2 Input Current_7 (A)": 8,
        "CSBPL IS1 Inverter3 Unit2 Input Current_8 (A)": 7.9,
        "CSBPL IS1 Inverter3 Unit2 Input Current_9 (A)": 7.9,
        "CSBPL IS1 Inverter3 Unit2 Input Current_10 (A)": 0,
        "CSBPL IS1 Inverter3 Unit2 Input Current_11 (A)": 0,
        "CSBPL IS1 Inverter3 Unit1 Input Current_1 (A)": 7.8,
        "CSBPL IS1 Inverter3 Unit1 Input Current_2 (A)": 7.7,
        "CSBPL IS1 Inverter3 Unit1 Input Current_3 (A)": 7.7,
        "CSBPL IS1 Inverter3 Unit1 Input Current_4 (A)": 7.9,
        "CSBPL IS1 Inverter3 Unit1 Input Current_5 (A)": 8.1,
        "CSBPL IS1 Inverter3 Unit1 Input Current_6 (A)": 7.3,
        "CSBPL IS1 Inverter3 Unit1 Input Current_7 (A)": 8,
        "CSBPL IS1 Inverter3 Unit1 Input Current_8 (A)": 7.1,
        "CSBPL IS1 Inverter3 Unit1 Input Current_9 (A)": 7.7,
        "CSBPL IS1 Inverter3 Unit1 Input Current_10 (A)": 0,
        "CSBPL IS1 Inverter3 Unit1 Input Current_11 (A)": 0,
        "CSBPL IS1 Inverter4 Unit1 Input Current_1 (A)": 7.7,
        "CSBPL IS1 Inverter4 Unit1 Input Current_2 (A)": 7.8,
        "CSBPL IS1 Inverter4 Unit1 Input Current_3 (A)": 7.8,
        "CSBPL IS1 Inverter4 Unit1 Input Current_4 (A)": 7.2,
        "CSBPL IS1 Inverter4 Unit1 Input Current_5 (A)": 7.9,
        "CSBPL IS1 Inverter4 Unit1 Input Current_6 (A)": 7.9,
        "CSBPL IS1 Inverter4 Unit1 Input Current_7 (A)": 7.8,
        "CSBPL IS1 Inverter4 Unit1 Input Current_8 (A)": 7.6,
        "CSBPL IS1 Inverter4 Unit1 Input Current_9 (A)": 7.4,
        "CSBPL IS1 Inverter4 Unit1 Input Current_10 (A)": 0,
        "CSBPL IS1 Inverter4 Unit1 Input Current_11 (A)": 0,
        "CSBPL IS1 Inverter4 Unit2 Input Current_1 (A)": 7.3,
        "CSBPL IS1 Inverter4 Unit2 Input Current_2 (A)": 7.6,
        "CSBPL IS1 Inverter4 Unit2 Input Current_3 (A)": 7.4,
        "CSBPL IS1 Inverter4 Unit2 Input Current_4 (A)": 7.6,
        "CSBPL IS1 Inverter4 Unit2 Input Current_5 (A)": 7.1,
        "CSBPL IS1 Inverter4 Unit2 Input Current_6 (A)": 0,
        "CSBPL IS1 Inverter4 Unit2 Input Current_7 (A)": 6.9,
        "CSBPL IS1 Inverter4 Unit2 Input Current_8 (A)": 6.8,
        "CSBPL IS1 Inverter4 Unit2 Input Current_9 (A)": 6.8,
        "CSBPL IS1 Inverter4 Unit2 Input Current_10 (A)": 7,
        "CSBPL IS1 Inverter4 Unit2 Input Current_11 (A)": 0,
    },


];
let tempdata = [];
let axis = Object.keys(data[0]).filter((x) => x !== "timestamp");
data.forEach((d) => {
    axis.forEach((axisvalue) => {
        tempdata.push({
            timestamp: d.timestamp,
            key: axisvalue,
            value: d[axisvalue],
        });
    });
});
