const data =
    [{
        "id": 1,
        "first_name": "Issiah",
        "last_name": "Swalwell",
        "email": "iswalwell0@eepurl.com",
        "gender": "Genderfluid",
        "ip_address": "65.237.204.65"
    }, {
        "id": 2,
        "first_name": "Kimberley",
        "last_name": "Adriaan",
        "email": "kadriaan1@accuweather.com",
        "gender": "Genderqueer",
        "ip_address": "11.145.133.177"
    }, {
        "id": 3,
        "first_name": "Clemmy",
        "last_name": "Derl",
        "email": "cderl2@istockphoto.com",
        "gender": "Bigender",
        "ip_address": "233.223.217.156"
    }, {
        "id": 4,
        "first_name": "Dare",
        "last_name": "Lummus",
        "email": "dlummus3@wix.com",
        "gender": "Polygender",
        "ip_address": "178.17.128.208"
    }, {
        "id": 5,
        "first_name": "Leona",
        "last_name": "Colisbe",
        "email": "lcolisbe4@naver.com",
        "gender": "Bigender",
        "ip_address": "217.131.216.68"
    }, {
        "id": 6,
        "first_name": "Anissa",
        "last_name": "Gladstone",
        "email": "agladstone5@nydailynews.com",
        "gender": "Genderqueer",
        "ip_address": "203.20.22.10"
    }, {
        "id": 7,
        "first_name": "Doralyn",
        "last_name": "Mazillius",
        "email": "dmazillius6@unicef.org",
        "gender": "Agender",
        "ip_address": "153.164.214.56"
    }, {
        "id": 8,
        "first_name": "Melisenda",
        "last_name": "Lintot",
        "email": "mlintot7@aboutads.info",
        "gender": "Genderfluid",
        "ip_address": "27.7.133.83"
    }, {
        "id": 9,
        "first_name": "Bunny",
        "last_name": "Beggio",
        "email": "bbeggio8@constantcontact.com",
        "gender": "Bigender",
        "ip_address": "243.47.115.231"
    }, {
        "id": 10,
        "first_name": "Deck",
        "last_name": "Spearing",
        "email": "dspearing9@photobucket.com",
        "gender": "Non-binary",
        "ip_address": "69.237.156.108"
    }, {
        "id": 11,
        "first_name": "Willey",
        "last_name": "Harring",
        "email": "wharringa@ibm.com",
        "gender": "Bigender",
        "ip_address": "191.121.119.179"
    }, {
        "id": 12,
        "first_name": "Emily",
        "last_name": "Sudron",
        "email": "esudronb@about.com",
        "gender": "Genderfluid",
        "ip_address": "38.200.131.7"
    }, {
        "id": 13,
        "first_name": "Rosaline",
        "last_name": "D'Ambrosio",
        "email": "rdambrosioc@ebay.co.uk",
        "gender": "Agender",
        "ip_address": "99.168.142.252"
    }, {
        "id": 14,
        "first_name": "Helli",
        "last_name": "Jendrassik",
        "email": "hjendrassikd@mapquest.com",
        "gender": "Bigender",
        "ip_address": "195.17.68.206"
    }, {
        "id": 15,
        "first_name": "Em",
        "last_name": "Peake",
        "email": "epeakee@ovh.net",
        "gender": "Bigender",
        "ip_address": "78.211.78.148"
    }, {
        "id": 16,
        "first_name": "Hendrik",
        "last_name": "Wethered",
        "email": "hwetheredf@uiuc.edu",
        "gender": "Bigender",
        "ip_address": "101.64.237.206"
    }, {
        "id": 17,
        "first_name": "Harlin",
        "last_name": "Casine",
        "email": "hcasineg@guardian.co.uk",
        "gender": "Genderfluid",
        "ip_address": "102.31.62.50"
    }, {
        "id": 18,
        "first_name": "Holly",
        "last_name": "Blase",
        "email": "hblaseh@huffingtonpost.com",
        "gender": "Genderqueer",
        "ip_address": "186.205.43.129"
    }, {
        "id": 19,
        "first_name": "Gwenni",
        "last_name": "Truett",
        "email": "gtruetti@privacy.gov.au",
        "gender": "Non-binary",
        "ip_address": "158.215.43.52"
    }, {
        "id": 20,
        "first_name": "Danell",
        "last_name": "Mosedill",
        "email": "dmosedillj@nature.com",
        "gender": "Male",
        "ip_address": "72.243.97.128"
    }, {
        "id": 21,
        "first_name": "Leonora",
        "last_name": "Speak",
        "email": "lspeakk@moonfruit.com",
        "gender": "Agender",
        "ip_address": "148.209.88.79"
    }, {
        "id": 22,
        "first_name": "Drusilla",
        "last_name": "Southcott",
        "email": "dsouthcottl@ebay.co.uk",
        "gender": "Genderfluid",
        "ip_address": "122.17.126.18"
    }, {
        "id": 23,
        "first_name": "Wynnie",
        "last_name": "Gehringer",
        "email": "wgehringerm@sohu.com",
        "gender": "Male",
        "ip_address": "27.121.172.29"
    }, {
        "id": 24,
        "first_name": "Antonino",
        "last_name": "Linner",
        "email": "alinnern@wikipedia.org",
        "gender": "Non-binary",
        "ip_address": "90.13.228.239"
    }, {
        "id": 25,
        "first_name": "Heida",
        "last_name": "McWhirter",
        "email": "hmcwhirtero@narod.ru",
        "gender": "Male",
        "ip_address": "155.191.68.75"
    }, {
        "id": 26,
        "first_name": "Lishe",
        "last_name": "Yair",
        "email": "lyairp@slate.com",
        "gender": "Non-binary",
        "ip_address": "240.97.206.229"
    }, {
        "id": 27,
        "first_name": "Christi",
        "last_name": "Sheppard",
        "email": "csheppardq@senate.gov",
        "gender": "Polygender",
        "ip_address": "200.92.117.105"
    }, {
        "id": 28,
        "first_name": "Mellicent",
        "last_name": "Dooly",
        "email": "mdoolyr@pcworld.com",
        "gender": "Female",
        "ip_address": "110.189.0.87"
    }, {
        "id": 29,
        "first_name": "Terra",
        "last_name": "Stenner",
        "email": "tstenners@icq.com",
        "gender": "Bigender",
        "ip_address": "4.85.51.170"
    }, {
        "id": 30,
        "first_name": "Lorenzo",
        "last_name": "MacIlhargy",
        "email": "lmacilhargyt@uiuc.edu",
        "gender": "Non-binary",
        "ip_address": "186.31.201.128"
    }, {
        "id": 31,
        "first_name": "Tera",
        "last_name": "Spinnace",
        "email": "tspinnaceu@cbslocal.com",
        "gender": "Agender",
        "ip_address": "244.134.192.40"
    }, {
        "id": 32,
        "first_name": "Wash",
        "last_name": "Swanborough",
        "email": "wswanboroughv@unblog.fr",
        "gender": "Bigender",
        "ip_address": "136.227.8.132"
    }, {
        "id": 33,
        "first_name": "Guinevere",
        "last_name": "Bovey",
        "email": "gboveyw@hhs.gov",
        "gender": "Polygender",
        "ip_address": "182.210.240.85"
    }, {
        "id": 34,
        "first_name": "Issy",
        "last_name": "McMaster",
        "email": "imcmasterx@yellowpages.com",
        "gender": "Male",
        "ip_address": "185.208.183.211"
    }, {
        "id": 35,
        "first_name": "Gauthier",
        "last_name": "Anton",
        "email": "gantony@github.io",
        "gender": "Female",
        "ip_address": "220.167.180.89"
    }, {
        "id": 36,
        "first_name": "Deanna",
        "last_name": "McGilben",
        "email": "dmcgilbenz@state.tx.us",
        "gender": "Male",
        "ip_address": "168.222.147.210"
    }, {
        "id": 37,
        "first_name": "Gilles",
        "last_name": "Dametti",
        "email": "gdametti10@prnewswire.com",
        "gender": "Bigender",
        "ip_address": "201.13.188.138"
    }, {
        "id": 38,
        "first_name": "Vin",
        "last_name": "Rivilis",
        "email": "vrivilis11@pinterest.com",
        "gender": "Polygender",
        "ip_address": "159.140.186.168"
    }, {
        "id": 39,
        "first_name": "Bank",
        "last_name": "Bullingham",
        "email": "bbullingham12@washingtonpost.com",
        "gender": "Genderqueer",
        "ip_address": "213.132.35.10"
    }, {
        "id": 40,
        "first_name": "Christi",
        "last_name": "Trittam",
        "email": "ctrittam13@phpbb.com",
        "gender": "Bigender",
        "ip_address": "159.220.82.117"
    }, {
        "id": 41,
        "first_name": "Noble",
        "last_name": "Brea",
        "email": "nbrea14@csmonitor.com",
        "gender": "Male",
        "ip_address": "160.171.197.221"
    }, {
        "id": 42,
        "first_name": "Harlene",
        "last_name": "Skarman",
        "email": "hskarman15@etsy.com",
        "gender": "Genderfluid",
        "ip_address": "147.204.71.9"
    }, {
        "id": 43,
        "first_name": "Domeniga",
        "last_name": "Gobbett",
        "email": "dgobbett16@wordpress.com",
        "gender": "Genderfluid",
        "ip_address": "216.83.0.42"
    }, {
        "id": 44,
        "first_name": "Cody",
        "last_name": "Andrioletti",
        "email": "candrioletti17@businessweek.com",
        "gender": "Male",
        "ip_address": "222.157.13.205"
    }, {
        "id": 45,
        "first_name": "Marie",
        "last_name": "Nanninini",
        "email": "mnanninini18@cdc.gov",
        "gender": "Agender",
        "ip_address": "163.167.207.233"
    }, {
        "id": 46,
        "first_name": "Ellsworth",
        "last_name": "Latan",
        "email": "elatan19@cbsnews.com",
        "gender": "Genderfluid",
        "ip_address": "124.43.185.229"
    }, {
        "id": 47,
        "first_name": "Isabelita",
        "last_name": "Hawford",
        "email": "ihawford1a@amazonaws.com",
        "gender": "Male",
        "ip_address": "92.51.196.159"
    }, {
        "id": 48,
        "first_name": "Kristan",
        "last_name": "Stoney",
        "email": "kstoney1b@about.com",
        "gender": "Bigender",
        "ip_address": "220.43.96.32"
    }, {
        "id": 49,
        "first_name": "Anthiathia",
        "last_name": "Jeffes",
        "email": "ajeffes1c@forbes.com",
        "gender": "Agender",
        "ip_address": "90.135.1.138"
    }, {
        "id": 50,
        "first_name": "Ambrose",
        "last_name": "Iddison",
        "email": "aiddison1d@tripod.com",
        "gender": "Non-binary",
        "ip_address": "111.77.176.62"
    }, {
        "id": 51,
        "first_name": "Curtis",
        "last_name": "Beggi",
        "email": "cbeggi1e@mapquest.com",
        "gender": "Genderfluid",
        "ip_address": "71.16.27.105"
    }, {
        "id": 52,
        "first_name": "Valina",
        "last_name": "Maffini",
        "email": "vmaffini1f@scientificamerican.com",
        "gender": "Male",
        "ip_address": "135.129.113.103"
    }, {
        "id": 53,
        "first_name": "Cosetta",
        "last_name": "Overell",
        "email": "coverell1g@behance.net",
        "gender": "Genderqueer",
        "ip_address": "167.43.165.220"
    }, {
        "id": 54,
        "first_name": "Shandee",
        "last_name": "Livingstone",
        "email": "slivingstone1h@businesswire.com",
        "gender": "Genderqueer",
        "ip_address": "248.196.0.232"
    }, {
        "id": 55,
        "first_name": "Wakefield",
        "last_name": "Sherred",
        "email": "wsherred1i@house.gov",
        "gender": "Non-binary",
        "ip_address": "25.124.244.69"
    }, {
        "id": 56,
        "first_name": "Armin",
        "last_name": "Ricardot",
        "email": "aricardot1j@zdnet.com",
        "gender": "Female",
        "ip_address": "153.177.188.172"
    }, {
        "id": 57,
        "first_name": "Niccolo",
        "last_name": "Chessill",
        "email": "nchessill1k@java.com",
        "gender": "Agender",
        "ip_address": "11.110.58.103"
    }, {
        "id": 58,
        "first_name": "Brittaney",
        "last_name": "Barnard",
        "email": "bbarnard1l@dyndns.org",
        "gender": "Bigender",
        "ip_address": "155.217.65.232"
    }, {
        "id": 59,
        "first_name": "Hadrian",
        "last_name": "Vanezis",
        "email": "hvanezis1m@tamu.edu",
        "gender": "Genderqueer",
        "ip_address": "216.1.147.114"
    }, {
        "id": 60,
        "first_name": "Ernie",
        "last_name": "Guido",
        "email": "eguido1n@ibm.com",
        "gender": "Non-binary",
        "ip_address": "234.195.78.127"
    }, {
        "id": 61,
        "first_name": "Trace",
        "last_name": "Halvorsen",
        "email": "thalvorsen1o@imdb.com",
        "gender": "Bigender",
        "ip_address": "102.148.86.58"
    }, {
        "id": 62,
        "first_name": "Wilma",
        "last_name": "Nelles",
        "email": "wnelles1p@cdc.gov",
        "gender": "Male",
        "ip_address": "191.102.250.231"
    }, {
        "id": 63,
        "first_name": "Doe",
        "last_name": "Miguet",
        "email": "dmiguet1q@wiley.com",
        "gender": "Male",
        "ip_address": "49.247.9.32"
    }, {
        "id": 64,
        "first_name": "Lauri",
        "last_name": "Hollingby",
        "email": "lhollingby1r@acquirethisname.com",
        "gender": "Genderfluid",
        "ip_address": "78.7.85.255"
    }, {
        "id": 65,
        "first_name": "Luz",
        "last_name": "Kissack",
        "email": "lkissack1s@fema.gov",
        "gender": "Female",
        "ip_address": "177.42.64.150"
    }, {
        "id": 66,
        "first_name": "Moss",
        "last_name": "Gollard",
        "email": "mgollard1t@netscape.com",
        "gender": "Bigender",
        "ip_address": "69.68.22.39"
    }, {
        "id": 67,
        "first_name": "Nana",
        "last_name": "Chiechio",
        "email": "nchiechio1u@redcross.org",
        "gender": "Polygender",
        "ip_address": "51.29.6.28"
    }, {
        "id": 68,
        "first_name": "Flore",
        "last_name": "Gebby",
        "email": "fgebby1v@slideshare.net",
        "gender": "Agender",
        "ip_address": "194.75.47.197"
    }, {
        "id": 69,
        "first_name": "Willamina",
        "last_name": "Nutbean",
        "email": "wnutbean1w@hc360.com",
        "gender": "Agender",
        "ip_address": "121.43.107.187"
    }, {
        "id": 70,
        "first_name": "Gregory",
        "last_name": "Kusick",
        "email": "gkusick1x@chicagotribune.com",
        "gender": "Genderfluid",
        "ip_address": "151.174.165.173"
    }, {
        "id": 71,
        "first_name": "Vladamir",
        "last_name": "O'Hederscoll",
        "email": "vohederscoll1y@dell.com",
        "gender": "Female",
        "ip_address": "42.200.166.188"
    }, {
        "id": 72,
        "first_name": "Deerdre",
        "last_name": "Schelle",
        "email": "dschelle1z@webs.com",
        "gender": "Genderfluid",
        "ip_address": "163.131.214.199"
    }, {
        "id": 73,
        "first_name": "Creigh",
        "last_name": "Epton",
        "email": "cepton20@shutterfly.com",
        "gender": "Non-binary",
        "ip_address": "246.246.49.93"
    }, {
        "id": 74,
        "first_name": "Harriett",
        "last_name": "Ivchenko",
        "email": "hivchenko21@buzzfeed.com",
        "gender": "Genderfluid",
        "ip_address": "249.17.83.127"
    }, {
        "id": 75,
        "first_name": "Kerby",
        "last_name": "McHaffy",
        "email": "kmchaffy22@nifty.com",
        "gender": "Genderfluid",
        "ip_address": "78.26.14.3"
    }, {
        "id": 76,
        "first_name": "Mario",
        "last_name": "Weight",
        "email": "mweight23@ebay.co.uk",
        "gender": "Agender",
        "ip_address": "60.207.97.213"
    }, {
        "id": 77,
        "first_name": "Giuseppe",
        "last_name": "Stirling",
        "email": "gstirling24@barnesandnoble.com",
        "gender": "Genderqueer",
        "ip_address": "167.5.2.3"
    }, {
        "id": 78,
        "first_name": "Keary",
        "last_name": "Freed",
        "email": "kfreed25@fotki.com",
        "gender": "Genderfluid",
        "ip_address": "149.157.199.79"
    }, {
        "id": 79,
        "first_name": "Abbe",
        "last_name": "Stidson",
        "email": "astidson26@typepad.com",
        "gender": "Genderqueer",
        "ip_address": "168.25.119.238"
    }, {
        "id": 80,
        "first_name": "Gradey",
        "last_name": "Ferry",
        "email": "gferry27@hhs.gov",
        "gender": "Non-binary",
        "ip_address": "119.56.197.232"
    }, {
        "id": 81,
        "first_name": "Arv",
        "last_name": "Titford",
        "email": "atitford28@flickr.com",
        "gender": "Bigender",
        "ip_address": "181.100.51.173"
    }, {
        "id": 82,
        "first_name": "Jorie",
        "last_name": "Handman",
        "email": "jhandman29@nhs.uk",
        "gender": "Bigender",
        "ip_address": "141.131.254.85"
    }, {
        "id": 83,
        "first_name": "Ernestus",
        "last_name": "Kinney",
        "email": "ekinney2a@mtv.com",
        "gender": "Female",
        "ip_address": "177.165.11.223"
    }, {
        "id": 84,
        "first_name": "Alys",
        "last_name": "Fredy",
        "email": "afredy2b@eventbrite.com",
        "gender": "Female",
        "ip_address": "65.181.183.24"
    }, {
        "id": 85,
        "first_name": "Evered",
        "last_name": "Bernardeau",
        "email": "ebernardeau2c@list-manage.com",
        "gender": "Agender",
        "ip_address": "54.133.21.119"
    }, {
        "id": 86,
        "first_name": "Lew",
        "last_name": "Bavester",
        "email": "lbavester2d@tmall.com",
        "gender": "Bigender",
        "ip_address": "191.99.143.46"
    }, {
        "id": 87,
        "first_name": "Alard",
        "last_name": "Plum",
        "email": "aplum2e@ehow.com",
        "gender": "Male",
        "ip_address": "102.76.40.212"
    }, {
        "id": 88,
        "first_name": "Hamid",
        "last_name": "Klimpke",
        "email": "hklimpke2f@webmd.com",
        "gender": "Non-binary",
        "ip_address": "149.248.184.84"
    }, {
        "id": 89,
        "first_name": "Pablo",
        "last_name": "O'Hollegan",
        "email": "pohollegan2g@ameblo.jp",
        "gender": "Genderqueer",
        "ip_address": "222.161.250.217"
    }, {
        "id": 90,
        "first_name": "Ynes",
        "last_name": "Evett",
        "email": "yevett2h@bing.com",
        "gender": "Genderqueer",
        "ip_address": "59.251.158.44"
    }, {
        "id": 91,
        "first_name": "Kipper",
        "last_name": "Scuffham",
        "email": "kscuffham2i@wikimedia.org",
        "gender": "Male",
        "ip_address": "108.16.190.174"
    }, {
        "id": 92,
        "first_name": "Margaretha",
        "last_name": "Coppock.",
        "email": "mcoppock2j@liveinternet.ru",
        "gender": "Genderfluid",
        "ip_address": "246.28.223.225"
    }, {
        "id": 93,
        "first_name": "Willette",
        "last_name": "Wadlow",
        "email": "wwadlow2k@telegraph.co.uk",
        "gender": "Polygender",
        "ip_address": "234.5.11.63"
    }, {
        "id": 94,
        "first_name": "June",
        "last_name": "Whinney",
        "email": "jwhinney2l@wunderground.com",
        "gender": "Non-binary",
        "ip_address": "124.19.24.112"
    }, {
        "id": 95,
        "first_name": "Peria",
        "last_name": "Wilcocks",
        "email": "pwilcocks2m@deliciousdays.com",
        "gender": "Male",
        "ip_address": "167.7.91.180"
    }, {
        "id": 96,
        "first_name": "Alvinia",
        "last_name": "Bodle",
        "email": "abodle2n@ask.com",
        "gender": "Polygender",
        "ip_address": "147.71.158.204"
    }, {
        "id": 97,
        "first_name": "Reid",
        "last_name": "St Ledger",
        "email": "rstledger2o@wunderground.com",
        "gender": "Male",
        "ip_address": "47.71.135.104"
    }, {
        "id": 98,
        "first_name": "Walt",
        "last_name": "Allsupp",
        "email": "wallsupp2p@answers.com",
        "gender": "Genderfluid",
        "ip_address": "161.51.183.159"
    }, {
        "id": 99,
        "first_name": "Alicia",
        "last_name": "Badrock",
        "email": "abadrock2q@pen.io",
        "gender": "Bigender",
        "ip_address": "47.121.105.12"
    }, {
        "id": 100,
        "first_name": "Reeva",
        "last_name": "Doveston",
        "email": "rdoveston2r@nps.gov",
        "gender": "Agender",
        "ip_address": "91.238.86.245"
    }]
var a = 10
var c = [1, 2, 3, 4, 5]
// c.forEach((x) => {
//     console.log(x)
// })
c.forEach(x => {
    console.log(x)
})


for (let [key, value] of data.entries()) {
    console.log(key); // This is the key;
    console.log(value); // This is the value;
}