const KPIAggregate = {
    plantkpi: {
        kwhExportTotal: {
            name: "kwhExportTotal",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_KWHEXPORTTOTAL",
            unit: "kWh",
            displayname: "Total Export Energy",
        },
        kwhImportTotal: {
            name: "kwhImportTotal",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_KWHIMPORTTOTAL",
            unit: "kWh",
            displayname: "Total Import Energy",
        },
        kwhNetExportTotal: {
            name: "kwhNetExportTotal",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_KWHNETEXPORTTOTAL",
            unit: "kWh",
            displayname: "Net Total Export Energy",
        },
        activepower: {
            name: "activepower",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_ACTIVEPOWER",
            unit: "kW",
            displayname: "Active Power",
        },
        peakpower: {
            name: "peakpower",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_PEAKPOWER",
            unit: "kW",
            displayname: "Peak Power",
        },
        kwhExport: {
            name: "kwhExport",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_KWHEXPORT",
            unit: "kW",
            displayname: "Export Energy",
        },
        kwhImport: {
            name: "kwhImport",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_KWHIMPORT",
            unit: "kW",
            displayname: "Import Energy",
        },
        kwhNetExport: {
            name: "kwhNetExport",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_KWHNETEXPORT",
            unit: "kWh",
            displayname: "Net Export Energy",
        },
        temperatureCorrectedPR: {
            name: "temperatureCorrectedPR",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_TEMPERATURECORRECTEDPR",
            unit: "%",
            displayname: "Temperature Corrected PR",
        },
        pr: {
            name: "pr",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_PR",
            unit: "%",
            displayname: "PR",
        },
        pa: {
            name: "pa",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_PA",
            unit: "%",
            displayname: "PA",
        },
        epa: {
            name: "epa",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_EPA",
            unit: "%",
            displayname: "Energy PA",
        },
        ga: {
            name: "ga",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_GA",
            unit: "%",
            displayname: "GA",
        },
        accuf: {
            name: "accuf",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_ACCUF",
            unit: "%",
            displayname: "AC CUF",
        },
        dccuf: {
            name: "dccuf",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_DCCUF",
            unit: "%",
            displayname: "DC CUF",
        },
        co2: {
            name: "co2",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_CO2",
            unit: "tonne",
            displayname: "CO2 Prevented",
        },
        gas: {
            name: "gas",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_GAS",
            unit: "Gallons",
            displayname: "Saved Gas",
        },
        coal: {
            name: "coal",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_COAL",
            unit: "tonne",
            displayname: "Saved Coal",
        },
        poa: {
            name: "poa",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_POA",
            unit: "kWh/m2",
            displayname: "POA",
        },
        yield: {
            name: "yield",
            function: undefined,
            formulaidentifier: "AGGREGATE_PLANTKPI_YIELD",
            unit: "kWh/kWp",
            displayname: "Yield",
        },
    },
    inverterkpi: {
        activepower: {
            name: "activepower",
            function: undefined,
            formulaidentifier: "AGGREGATE_INVERTERKPI_ACTIVEPOWER",
            unit: "kW",
            displayname: "Active Power",
        },
        kwhExport: {
            name: "kwhExport",
            function: undefined,
            formulaidentifier: "AGGREGATE_INVERTERKPI_KWHEXPORT",
            unit: "kWh",
            displayname: "Export Energy",
        },
        kwhExportTotal: {
            name: "kwhExportTotal",
            function: undefined,
            formulaidentifier: "AGGREGATE_INVERTERKPI_KWHEXPORTTOTAL",
            unit: "kWh",
            displayname: "Total Export Energy",
        },
        capacity: {
            name: "capacity",
            function: undefined,
            formulaidentifier: "AGGREGATE_INVERTERKPI_CAPACITY",
            unit: "kW",
            displayname: "Inverter Capacity",
        },
        downtime: {
            name: "downtime",
            function: undefined,
            formulaidentifier: "AGGREGATE_INVERTERKPI_DOWNTIME",
            unit: "minutes",
            displayname: "Inverter Down Time",
        },
        ia: {
            name: "ia",
            function: undefined,
            formulaidentifier: "AGGREGATE_INVERTERKPI_IA",
            unit: "%",
            displayname: "Inverter Availability",
        },
        eia: {
            name: "eia",
            function: undefined,
            formulaidentifier: "AGGREGATE_INVERTERKPI_EIA",
            unit: "%",
            displayname: "Energy Inverter Availability",
        },
        efficiency: {
            name: "efficiency",
            function: undefined,
            formulaidentifier: "AGGREGATE_INVERTERKPI_EFFICIENCY",
            unit: "%",
            displayname: "Efficiency",
        },
    },
    meterkpi: {
        kwhExportTotal: {
            name: "kwhExportTotal",
            function: undefined,
            formulaidentifier: "AGGREGATE_METERKPI_KWHEXPORTTOTAL",
            unit: "kWh",
            displayname: "Total Export Energy",
        },
        kwhImportTotal: {
            name: "kwhImportTotal",
            function: undefined,
            formulaidentifier: "AGGREGATE_METERKPI_KWHIMPORTTOTAL",
            unit: "kWh",
            displayname: "Total Import Energy",
        },
        kwhNetExportTotal: {
            name: "kwhNetExportTotal",
            function: undefined,
            formulaidentifier: "AGGREGATE_METERKPI_KWHNETEXPORTTOTAL",
            unit: "kWh",
            displayname: "Net Total Export Energy",
        },
        activepower: {
            name: "activepower",
            function: undefined,
            formulaidentifier: "AGGREGATE_METERKPI_ACTIVEPOWER",
            unit: "kW",
            displayname: "Active Power",
        },
        peakpower: {
            name: "peakpower",
            function: undefined,
            formulaidentifier: "AGGREGATE_METERKPI_PEAKPOWER",
            unit: "kW",
            displayname: "Peak Power",
        },
        kwhExport: {
            name: "kwhExport",
            function: undefined,
            formulaidentifier: "AGGREGATE_METERKPI_KWHEXPORT",
            unit: "kWh",
            displayname: "Net Export Energy",
        },
        kwhImport: {
            name: "kwhImport",
            function: undefined,
            formulaidentifier: "AGGREGATE_METERKPI_KWHIMPORT",
            unit: "kWh",
            displayname: "Export Energy",
        },
        kwhNetExport: {
            name: "kwhNetExport",
            function: undefined,
            formulaidentifier: "AGGREGATE_METERKPI_KWHNETEXPORT",
            unit: "kWh",
            displayname: "Net Export Energy",
        },
    },
};
console.log(KPIAggregate)