await functionbuilder(
    req.dbconnection,
    {
        devicebusiness,
        settingbusiness,
        reportbusiness,
        blockbusiness,
        blockdevicedata,
        inverterunitunavailabilitybusiness,
        prdatabusiness,
        devicetypeEnum,
        getData,
        prreport,
        blockdevicedatamodel,
    },
    {
        log,
        lodash,
        startOfDay,
        endOfDay,
        parse,
        differenceInMinutes,
        differenceInDays,
        format,
        util,
        XLSX,
        workbook,
        fs,
        res,
        req,
        PDFDocument,
    },
    {
        startdate: startOfDay(new Date(userinput.starttime)),
        enddate: endOfDay(new Date(userinput.endtime)),
        settingdata,
    }
);