const lodash = require("lodash");
const fs = require("fs");
// const arrayOfObjCopy = [...arrayOfObj];

// Object.keys(arrayOfObjCopy).forEach((key) => {
//   arrayOfObjCopy[key] = JSON.stringify(arrayOfObjCopy[key]);
//  });
// const dataval = [
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "MFM",
//       devicetypeid: "25",
//       devicecode: 55461091,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "MFM",
//       deviceprotocol: "5",
//       devicemake: "NA",
//       devicemodel: "NA",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "VCB",
//       devicetypeid: "27",
//       devicecode: 7921911,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "VCB",
//       deviceprotocol: "5",
//       devicemake: "Schneider",
//       devicemodel: "Schneider",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "Inverter 1",
//       devicetypeid: "3",
//       devicecode: 66232187,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "INV_1",
//       deviceprotocol: "5",
//       devicemake: "Schneider",
//       devicemodel: "Conext Core XC 680",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "Relay",
//       devicetypeid: "11",
//       devicecode: 16149308,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "RELY",
//       deviceprotocol: "5",
//       devicemake: "Schneider",
//       devicemodel: "Schneider",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "Inverter 2",
//       devicetypeid: "3",
//       devicecode: 10821039,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "INV_2",
//       deviceprotocol: "5",
//       devicemake: "Schneider",
//       devicemodel: "Conext Core XC 680",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "UPS",
//       devicetypeid: "9",
//       devicecode: 81114935,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "UPS",
//       deviceprotocol: "5",
//       devicemake: "NA",
//       devicemodel: "NA",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "WMS",
//       devicetypeid: "7",
//       devicecode: 65808881,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "WMS",
//       deviceprotocol: "5",
//       devicemake: "Kipp & Zonen",
//       devicemodel: "CMP11",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 20",
//       devicetypeid: "6",
//       devicecode: 7724321,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_20",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 3",
//       devicetypeid: "6",
//       devicecode: 75557181,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_3",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 1",
//       devicetypeid: "6",
//       devicecode: 58761593,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_1",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 4",
//       devicetypeid: "6",
//       devicecode: 7783381,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_4",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 2",
//       devicetypeid: "6",
//       devicecode: 85761463,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_2",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 6",
//       devicetypeid: "6",
//       devicecode: 50658050,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_6",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 5",
//       devicetypeid: "6",
//       devicecode: 71910377,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_5",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 8",
//       devicetypeid: "6",
//       devicecode: 50021823,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_8",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 9",
//       devicetypeid: "6",
//       devicecode: 69264584,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_9",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 10",
//       devicetypeid: "6",
//       devicecode: 11662238,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_10",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 11",
//       devicetypeid: "6",
//       devicecode: 9187558,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_11",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 12",
//       devicetypeid: "6",
//       devicecode: 46345340,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_12",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 14",
//       devicetypeid: "6",
//       devicecode: 35175957,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_14",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 13",
//       devicetypeid: "6",
//       devicecode: 72704261,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_13",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 15",
//       devicetypeid: "6",
//       devicecode: 70238710,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_15",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 16",
//       devicetypeid: "6",
//       devicecode: 23538770,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_16",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 7",
//       devicetypeid: "6",
//       devicecode: 52291025,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_7",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 19",
//       devicetypeid: "6",
//       devicecode: 12863601,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_19",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "SCB 17",
//       devicetypeid: "6",
//       devicecode: 62602671,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "SCB_17",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "ARUL",
//       devicetypeid: "6",
//       devicecode: 22922987,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "ARUL_4",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "ARUL",
//       devicetypeid: "6",
//       devicecode: 62521467,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "ARUL_2",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "ARUL",
//       devicetypeid: "6",
//       devicecode: 24683143,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "ARUL_3",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "ARUL",
//       devicetypeid: "6",
//       devicecode: 62009098,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "ARUL_22",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "ARUL",
//       devicetypeid: "6",
//       devicecode: 11990358,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "ARUL_33",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "ARUL",
//       devicetypeid: "6",
//       devicecode: 18282862,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "ARUL_24",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "ARUL",
//       devicetypeid: "6",
//       devicecode: 78355233,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "ARUL_34",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "ARUL",
//       devicetypeid: "6",
//       devicecode: 80361236,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "ARUL_25",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "ARUL",
//       devicetypeid: "6",
//       devicecode: 60016744,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "ARUL_27",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "ARUL",
//       devicetypeid: "6",
//       devicecode: 83265604,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "ARUL_37",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "ARUL",
//       devicetypeid: "6",
//       devicecode: 28961164,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "ARUL_57",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//     {
//       _id: undefined,
//       plantid: "62fb73682b679ae1c70d34e9",
//       deviceip: "10.2.101.126",
//       deviceport: "51310",
//       devicedatafetchcron: "*/1 * * * *",
//       devicedisplayname: "ARUL",
//       devicetypeid: "6",
//       devicecode: 38933921,
//       devicesortorder: "9999",
//       blockid: "63074a1456c0c57076e08a8e",
//       deviceparentid: undefined,
//       devicestatus: {
//         communicationalarmenabled: true,
//         communicationeventenabled: true,
//         disable: true,
//         hidden: true,
//       },
//       devicemeta: {
//         othermeta: {
//         },
//         opcua: {
//           securitypolicy: "http://opcfoundation.org/UA/SecurityPolicy#None",
//           securitymode: "1",
//           endpoint: "/CogentDataHub/DataAccess",
//           username: undefined,
//           password: undefined,
//         },
//       },
//       devicename: "ARUL_67",
//       deviceprotocol: "5",
//       devicemake: "Adarsha",
//       devicemodel: "Adarsha",
//       devicevirtual: true,
//     },
//   ]
// const arrayOfObjhasDuplicates = lodash.uniq(dataval).length != dataval.length;
// console.log(arrayOfObjhasDuplicates)

genRandomString = (length = 256) => {
  const chars =
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

  const randomArray = Array.from(
    { length },

    () => chars[Math.floor(Math.random() * chars.length)]
  );
  const randomString = randomArray.join("");
  return randomString;
};
generateRandomCode = (existingIDs) => {
  const tempString = genRandomString(8).toLowerCase();
  const tempStringExists = existingIDs.filter(
    (ele) => ele.jobtemplateid === tempString
  );

  if (tempStringExists && tempStringExists.length > 0) {
    generateRandomCode(existingIDs);
  }

  return tempString;
};
const a = [];
for (let i = 0; i < 100000; i++) {
  a.push(generateRandomCode(a));
}

const arrayOfObjhasDuplicates = a.map((x, i) => {
  return { label: x, value: x };
});
console.log(arrayOfObjhasDuplicates);
try {
  fs.writeFileSync(
    `./uniq_${new Date().getTime()}.json`,
    JSON.stringify(arrayOfObjhasDuplicates)
  );
  // file written successfully
} catch (err) {
  console.error(err);
}
