
const data = [
    {
        plant: "A01 PSEPL",
        energy_actual: 0,
        energy_expected: 0,
        energy_dev: 0,
        irr_actual: 0,
        irr_expected: 7.16,
        irr_dev: -100,
        pa_actual: 0,
        pa_expected: 99.5,
        pa_dev: -100,
        ga_actual: 0,
        ga_expected: 0,
        ga_dev: 0,
        pr_actual: 0,
        pr_expected: 71.5,
        pr_dev: -100,
        dccuf_actual: 0,
        dccuf_expected: 0,
        dccuf_dev: 0,
    },
    {
        plant: "A02 NSPPL",
        energy_actual: 0,
        energy_expected: 0,
        energy_dev: 0,
        irr_actual: 0,
        irr_expected: 6.83,
        irr_dev: -100,
        pa_actual: 0,
        pa_expected: 99.5,
        pa_dev: -100,
        ga_actual: 0,
        ga_expected: 0,
        ga_dev: 0,
        pr_actual: 0,
        pr_expected: 78.09,
        pr_dev: -100,
        dccuf_actual: 0,
        dccuf_expected: 0,
        dccuf_dev: 0,
    },
    {
        plant: "A03 SSPPL",
        energy_actual: 0,
        energy_expected: 0,
        energy_dev: 0,
        irr_actual: 0,
        irr_expected: 7.34,
        irr_dev: -100,
        pa_actual: 0,
        pa_expected: 99.5,
        pa_dev: -100,
        ga_actual: 0,
        ga_expected: 0,
        ga_dev: 0,
        pr_actual: 0,
        pr_expected: 75.63,
        pr_dev: -100,
        dccuf_actual: 0,
        dccuf_expected: 0,
        dccuf_dev: 0,
    },
    {
        plant: "A04 SDPIPL",
        energy_actual: 0,
        energy_expected: 0,
        energy_dev: 0,
        irr_actual: 0,
        irr_expected: 6.92,
        irr_dev: -100,
        pa_actual: 0,
        pa_expected: 99.5,
        pa_dev: -100,
        ga_actual: 0,
        ga_expected: 0,
        ga_dev: 0,
        pr_actual: 0,
        pr_expected: 75.27,
        pr_dev: -100,
        dccuf_actual: 0,
        dccuf_expected: 0,
        dccuf_dev: 0,
    },
    {
        plant: "A05 SPPL",
        energy_actual: 0,
        energy_expected: 0,
        energy_dev: 0,
        irr_actual: 0,
        irr_expected: 6.59,
        irr_dev: -100,
        pa_actual: 0,
        pa_expected: 99.5,
        pa_dev: -100,
        ga_actual: 0,
        ga_expected: 0,
        ga_dev: 0,
        pr_actual: 0,
        pr_expected: 75.78,
        pr_dev: -100,
        dccuf_actual: 0,
        dccuf_expected: 0,
        dccuf_dev: 0,
    },
    {
        plant: "A06 SUPL",
        energy_actual: 0,
        energy_expected: 0,
        energy_dev: 0,
        irr_actual: 0,
        irr_expected: 6.66,
        irr_dev: -100,
        pa_actual: 0,
        pa_expected: 99.5,
        pa_dev: -100,
        ga_actual: 0,
        ga_expected: 0,
        ga_dev: 0,
        pr_actual: 0,
        pr_expected: 75.22,
        pr_dev: -100,
        dccuf_actual: 0,
        dccuf_expected: 0,
        dccuf_dev: 0,
    },
    {
        plant: "A07 SSEPL",
        energy_actual: 0,
        energy_expected: 0,
        energy_dev: 0,
        irr_actual: 0,
        irr_expected: 0,
        irr_dev: 0,
        pa_actual: 0,
        pa_expected: 99.5,
        pa_dev: -100,
        ga_actual: 0,
        ga_expected: 0,
        ga_dev: 0,
        pr_actual: 0,
        pr_expected: 0,
        pr_dev: 0,
        dccuf_actual: 0,
        dccuf_expected: 0,
        dccuf_dev: 0,
    },
    {
        plant: "A08 USUPL",
        energy_actual: 0,
        energy_expected: 0,
        energy_dev: 0,
        irr_actual: 0,
        irr_expected: 0,
        irr_dev: 0,
        pa_actual: 0,
        pa_expected: 99.5,
        pa_dev: -100,
        ga_actual: 0,
        ga_expected: 0,
        ga_dev: 0,
        pr_actual: 0,
        pr_expected: 0,
        pr_dev: 0,
        dccuf_actual: 0,
        dccuf_expected: 0,
        dccuf_dev: 0,
    },
    {
        plant: "A09 NSUPL",
        energy_actual: 0,
        energy_expected: 0,
        energy_dev: 0,
        irr_actual: 0,
        irr_expected: 0,
        irr_dev: 0,
        pa_actual: 0,
        pa_expected: 99.5,
        pa_dev: -100,
        ga_actual: 0,
        ga_expected: 0,
        ga_dev: 0,
        pr_actual: 0,
        pr_expected: 0,
        pr_dev: 0,
        dccuf_actual: 0,
        dccuf_expected: 0,
        dccuf_dev: 0,
    },
    {
        plant: "A10 SSUPL",
        energy_actual: 0,
        energy_expected: 0,
        energy_dev: 0,
        irr_actual: 0,
        irr_expected: 0,
        irr_dev: 0,
        pa_actual: 0,
        pa_expected: 99.5,
        pa_dev: -100,
        ga_actual: 0,
        ga_expected: 0,
        ga_dev: 0,
        pr_actual: 0,
        pr_expected: 0,
        pr_dev: 0,
        dccuf_actual: 0,
        dccuf_expected: 0,
        dccuf_dev: 0,
    },
    {
        plant: "A11 ESPL",
        energy_actual: 0,
        energy_expected: 0,
        energy_dev: 0,
        irr_actual: 0,
        irr_expected: 6.23,
        irr_dev: -100,
        pa_actual: 0,
        pa_expected: 99.5,
        pa_dev: -100,
        ga_actual: 0,
        ga_expected: 0,
        ga_dev: 0,
        pr_actual: 0,
        pr_expected: 75.92,
        pr_dev: -100,
        dccuf_actual: 0,
        dccuf_expected: 0,
        dccuf_dev: 0,
    },
    {
        plant: "A12 SPUPL",
        energy_actual: 0,
        energy_expected: 0,
        energy_dev: 0,
        irr_actual: 0,
        irr_expected: 0,
        irr_dev: 0,
        pa_actual: 0,
        pa_expected: 99.5,
        pa_dev: -100,
        ga_actual: 0,
        ga_expected: 0,
        ga_dev: 0,
        pr_actual: 0,
        pr_expected: 0,
        pr_dev: 0,
        dccuf_actual: 0,
        dccuf_expected: 0,
        dccuf_dev: 0,
    },
];

const keys = [
    "plant",
    "energy_actual",
    "energy_expected",
    "energy_dev",
    "irr_actual",
    "irr_expected",
    "irr_dev",
    "pa_actual",
    "pa_expected",
    "pa_dev",
    "ga_actual",
    "ga_expected",
    "ga_dev",
    "pr_actual",
    "pr_expected",
    "pr_dev",
    "dccuf_actual",
    "dccuf_expected",
    "dccuf_dev",
];

let temp = [];

keys.forEach((keystring) => {
    switch (keystring) {
        case ("irr_actual", "irr_expected", "energy_actual", "energy_expected"):
            const a = lodash.sumBy(data, (x) => x[keystring]);

            temp.push(a);

            break;

        case ("irr_dev",
            "ga_dev",
            "pa_dev",
            "dccuf_dev",
            "pr_dev",
            "energy_dev",
            "irr_dev"):
            const b = lodash.meanBy(data, (x) => x[keystring] !== "NA");

            temp.push(b);

            break;

        default:
            let c = lodash.meanBy(data, (x) => x[keystring])
            c = isNaN(c) ? '' : c;

            temp.push(c);

            break;
    }
});

